using GeneratedCodeAttribute = global::System.CodeDom.Compiler.GeneratedCodeAttribute;
using Wrapper_IDependency = global::TestsHelper.SourceGenerator.Tests.TestsCases.GenerateMocks.Source.Wrapper_IDependency;
using TestedClass = global::TestsHelper.SourceGenerator.Tests.TestsCases.Base.TestedClass;
using Mock_IDependency = global::Moq.Mock<global::TestsHelper.SourceGenerator.Tests.TestsCases.Base.IDependency>;

// <auto-generated/>
namespace TestsHelper.SourceGenerator.Tests.TestsCases.GenerateMocks.Source
{
    [GeneratedCodeAttribute("TestsHelper.SourceGenerator", "3.0.0.0")]
    public partial class Test
    {
        private Wrapper_IDependency _dependency;
        private TestedClass Build()
        {
            _dependency = new Wrapper_IDependency(new Mock_IDependency());
            return new TestedClass(_dependency.Mock.Object, _nullFactory);
        }
    }
}