using GeneratedCodeAttribute = global::System.CodeDom.Compiler.GeneratedCodeAttribute;
using Mock_IDependency = global::Moq.Mock<global::TestsHelper.SourceGenerator.Tests.TestsCases.Base.IDependency>;

// <auto-generated/>
namespace TestsHelper.SourceGenerator.Tests.TestsCases.GenerateMocks.Source
{
    [GeneratedCodeAttribute("TestsHelper.SourceGenerator", "3.0.0.0")]
    public class Wrapper_IDependency
    {
        public Mock_IDependency Mock { get; }

        public Wrapper_IDependency(Mock_IDependency mock)
        {
            Mock = mock;
        }
    }
}