name: Release

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
      - name: Pack
        run: dotnet pack -c Release --no-build -o nupkgs
      - name: print
        run: ls
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: nupkgs/*
          if-no-files-found: error
