name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/CI.yml
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Install Zip
        run: sudo apt-get install zip
      - run: zip -r -j dependencies.zip packages/**/*/*.nupkg
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files:  |
            ${{ github.workspace }}/nupkgs/*.nupkg
            ${{ github.workspace }}/dependencies.zip
          tag_name: ${{ steps.tagName.outputs.tag }}